apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedapi
  labels:
    app: feedapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedapi
  template:
    metadata:
      labels:
        app: feedapi
    spec:
      containers:
        - name: feedapi
          image: ghcr.io/s3nthilg0pal/feedapi:latest
          ports:
            - containerPort: 8080
