apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedapi
  labels:
    app: feedapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedapi
  template:
    metadata:
      labels:
        app: feedapi
    spec:
      containers:
        - name: feedapi
          image: ghcr.io/s3nthilg0pal/feedapi:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
