apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedapirest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedapirest
  template:
    metadata:
      labels:
        app: feedapirest
    spec:
      containers:
        - name: feedapirest
          image: feed-api-rest
          pports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
