apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: feed-api-rest
    newName: ghcr.io/s3nthilg0pal/feedapi
    newTag: latest
