name: Publish to GitHub Container Registry

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: feedapi
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # adjust to your version

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $REGISTRY/$OWNER/$IMAGE_NAME:latest .
          docker push $REGISTRY/$OWNER/$IMAGE_NAME:latest
